galaxy_info:
  role_name: "docker"
  author: xue.zeng
  description: Docker for Linux.
  company: "Accenture"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
  - name: CentOS
    versions:
    - 7

  galaxy_tags:
    - containers
    - docker
    - system

dependencies: []