# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$num_instances = 3

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
    (1..$num_instances).each do |id|
    config.vm.define "node#{id}" do |node|
      node.vm.box="centos/7"
      node.ssh.insert_key = false
      node.vm.hostname = "node#{id}"
      node.vm.network :private_network, ip: "192.168.61.#{id+10}"
      node.vm.provider :virtualbox do |vb, override|
        vb.name = "node#{id}"
        vb.gui = false
        vb.memory = 4096
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "scripts/bootstrap_kubernetes_base_centos.sh"
    end
  end
end
