eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8086

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/x-_-space/config-repo
          username: xue.zeng
          password: 