server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    test-on-borrow: false
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    time-between-eviction-runs-millis: 600000
