## ---------docker daemon配置部分-----------

## 准备docker相关目录
- name: Create install dir
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - /etc/docker

## 下载 docker 二进制文件
- name: Download or upload tarball
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - docker-containerd
  - docker-containerd-shim
  - docker-init
  - docker-runc
  - docker
  - docker-containerd-ctr
  - dockerd
  - docker-proxy
  tags: upgrade_docker, download_docker

## docker命令自动补全
- name: docker command auto completion
  copy: src=docker dest=/etc/bash_completion.d/docker mode=0644

## docker国内镜像加速
- name: Docker domestic image acceleration
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: flush-iptables
  shell: "iptables -F && iptables -X \
        && iptables -F -t nat && iptables -X -t nat \
        && iptables -F -t raw && iptables -X -t raw \
        && iptables -F -t mangle && iptables -X -t mangle"

## 创建docker的systemd unit文件
- name: Create docker systemd unit file
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
  tags: upgrade_docker, download_docker

## 开机启用docker 服务
- name: Turn on the docker service
  shell: systemctl enable docker
  ignore_errors: true

## 开启docker 服务
- name: Open the docker service
  shell: systemctl daemon-reload && systemctl restart docker
  tags: upgrade_docker

## 可选 ------安装docker查询镜像 tag的小工具----
# 先要安装轻量JSON处理程序‘jq’，已在 prepare 节点安装
##- name: 下载 docker-tag
##  copy: src=docker-tag dest={{ bin_dir }}/docker-tag mode=0755